### ISSUE TITLE
Collections for text types

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-instance-nomansland-dev#4]
In the vanialla instance of Nomansland, the text type object is assigned collections
![image](https://github.com/acdh-oeaw/apis-instance-nomansland-dev/assets/7236469/4c2ef615-762c-4320-9b0a-5c7496108bb8)

In the current data model these texts are attributes of the entities themselves, and while entities can be put in collections, the text types cannot be (text types exist in the form of field names, such as `apis_ontology.manuscript.illustration_notes`

Is this a problem?

**Comment by sennierer** [comment]
ah...sorry missed that. no thats not a problem. the collection in this case only means that the texttype (its a texttype and not the text itself) should be shown in all objects that are in one of these collections. This made it possible to have different text types enabled in different collections. to sum up: this information is not needed anymore in the new instance.
